-- SIGAPP NTT full table
create table if not exists public.sekolah_ntt_full (
  id bigint generated by default as identity primary key,
  school_name text,
  npsn text,
  jenjang text,
  kabupaten text,
  kecamatan text,
  kelurahan text,
  provinsi text,
  addr_city text,
  addr_street text,
  operator text,
  lat double precision not null,
  lon double precision not null,
  total_students integer,
  total_teachers integer,
  sigapp_index numeric,
  p1_quality_gap numeric,
  p2_spatial_inequity numeric,
  p3_structural_risk numeric,
  p4_public_signal numeric,
  index_notes text,
  computed_at timestamptz,
  teacher_ratio numeric,
  facility_score numeric,
  nearest_school_km numeric,
  disaster_risk_score numeric,
  internet_access boolean,
  remote_status boolean
);

create index if not exists idx_sekolah_ntt_full_kabupaten on public.sekolah_ntt_full (kabupaten);
create index if not exists idx_sekolah_ntt_full_jenjang on public.sekolah_ntt_full (jenjang);
create index if not exists idx_sekolah_ntt_full_sigapp_index on public.sekolah_ntt_full (sigapp_index);
create index if not exists idx_sekolah_ntt_full_npsn on public.sekolah_ntt_full (npsn);